properly parsing ipv4 addresses
slamdata/purescript-uri pull request #21
Opened 2017-06-22 16:46 UTC by athanclark

2017-06-22 16:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slamdata/purescript-uri?pullRequest=21) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slamdata/purescript-uri?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slamdata/purescript-uri?pullRequest=21) it.</sub>

2017-06-23 11:40 UTC, garyb requested changes
Looks like there's a unnecessary import that is making Travis fail. I'll get this released once that is fixed up :)

2017-06-24 15:32 UTC, athanclark commented
Oop sorry, just saw that.

2017-06-24 15:43 UTC, garyb approved these changes

2017-06-24 15:43 UTC, merged